services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: minha_api_user
      POSTGRES_PASSWORD: minha_api_pass
      POSTGRES_DB: minha_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
